### PR TITLE
Set image_raw_formatter as dependency and use URL formatter in view

### PR DESCRIPTION
**Pull request by yannickoo**
This PR adds the Image URL Formatter as dependency and makes use of it in the employees view.

### CODE REVIEW

**Comment by pcambra** [comment]
Let's add the modules in the makefile in the wundersites_dev profile

**Comment by yannickoo** [comment]
I removed the commit for adding the submodule :)

**Comment by pcambra** [comment]
I think the commit removed is the other one and the submodule change is still there

**Comment by yannickoo** [comment]
Sorry for the confusion, looks better now.

**Pull request closed without merging**
