### PR TITLE
Add Case Studies support with wkhub_casestudies module

### PR DESCRIPTION
**Pull request by joesb**
Content type and Views REST view

### CODE REVIEW

**Comment by lewisnyman** [comment]
I'm getting errors on install. I guess this needs a rebase as well.
```
Starting Drupal installation. This takes a while. Consider using the --notify global option.             [ok]
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects            [error]
(field.field.node.case_study.field_country, field.field.node.case_study.field_image,
field.field.node.case_study.field_intro, field.field.node.case_study.field_kicker,
views.view.case_studies) provided by wkhub_casestudies have unmet dependencies' in
/vagrant/drupal/current/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:89
```

**Comment by joesb** [comment]
Curious. Ok, I'll check it out.

**Comment by joesb** [comment]
Aah, it has a dependency on wkhub_blogs module, so I guess that PR #26 needs to be merged before this one will install.

**Comment by lewisnyman** [comment]
Now that #26 is merged. You can rebase this then I should be able to test it.

**Comment by joesb** [comment]
Hmm, not quite a rebase - I used the wrong syntax. Doh.

**Comment by joesb** [comment]
On fire!

**Pull request merged**
