### PR TITLE
add sort by first name to team listing view

### PR DESCRIPTION
**Pull request by yannickoo**
In order to display team members alphabetically we need to add a sort behavior to the view.

### CODE REVIEW

**Comment by pcambra** [comment]
I had forgotten about this one, sorry. Can we revert this change? the sorting is happening in the client module instead.

**Comment by lewisnyman** [comment]
Ah ok

**Comment by yannickoo** [comment]
Okay but why should the API return team members in such an order? Sorting by first name is absolutely okay isn't it? :/

**Comment by pcambra** [comment]
It is a setting in the frontend module now.

**Pull request merged**
