### PR TITLE
Add a submodule for WunderPrinciples content type and API endpoints

### PR DESCRIPTION
**Pull request by joesb**
This is mostly about me learning some D8 stuff, but also a nice bonus to the WunderHub API. Adds a Principles content type and Views API paths api/principles, api/principles/{uuid}

BUT, also custom code to add a WunderPrinciples zen API endpoint, in the style of https://api.github.com/zen, at api/principles/zen

### CODE REVIEW

**Comment by joesb** [comment]
This PR needs to be reviewed *after* #24 gets merged

**Comment by lewisnyman** [comment]
Hmm I get a weird error when trying to install this profile:

Starting Drupal installation. This takes a while. Consider using the --notify global option.             [ok]
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects            [error]
(core.entity_form_display.user.user.default, views.view.team_listing) provided by wkhub_person have unmet
dependencies' in /vagrant/drupal/current/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:89
Stack trace:
#0 /vagrant/drupal/c

**Comment by joesb** [comment]
Aah, maybe this is because the PR is based on the work prior to #24 - I probably need to rebase or something?

**Comment by lewisnyman** [comment]
This works great. The only suggestions I would make is:
1. Including the principle description under api/zen, maybe we can use markdown formatting and a line break here?
2. Filtering the principle endpoint by title instead of uuid. I think it would be much cleaner. I'm happy to open issues for these improvements though.

**Comment by joesb** [comment]
On your point 1, my build was following the style of https://api.github.com/zen, which only gives the one line, randomly from the options, and does not even return it as JSON data.

For me, the api/principles/zen endpoint is more an easter egg.

**Comment by joesb** [comment]
On your point 2, I just wonder whether that could cause a problem given that the titles won't necessarily be stable - someone edits a title and the data URL disappears

**Comment by joesb** [comment]
We can easily add URL query options for filtering by title, tho

**Comment by lewisnyman** [comment]
1. Ok cool, that makes sense.
2. Ok good point, I guess it needs some more thought and planning. Drupal usually maintains content alias' for titles that change right?

**Pull request merged**
