### PR TITLE
Add user profile fields (link fields) for Twitter, Github, Drupal.org

### LINKED ISSUE #22: Add profile links
Profile links to:
Twitter
Github
Drupal.org
Anything else?

### PR DESCRIPTION
**Pull request by joesb**
Add fields in /api/team data. Requires field_group module.

Fixes #22

### CODE REVIEW

**Comment by joesb** [comment]
**Note:** When deploying this to production, the [field_group](https://www.drupal.org/project/field_group) module needs to be installed.

Cf. wunderkraut/wundersites_dev#11

**Comment by lewisnyman** [comment]
This gives me an install error:

```
PHP Fatal error:  Call to a member function getPath() on a non-object in /vagrant/drupal/current/core/includes/install.inc on line 931
PHP Stack trace:
PHP   1. {main}() /usr/lib/composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /usr/lib/composer/vendor/drush/drush/drush.php:11
PHP   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /usr/lib/composer/vendor/drush/drush/drush.php:70
PHP   4. drush_dispatch() /usr/lib/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:62
PHP   5. call_user_func_array:{/usr/lib/composer/vendor/drush/drush/includes/command.inc:178}() /usr/lib/composer/vendor/drush/drush/includes/command.inc:178
PHP   6. drush_command() /usr/lib/composer/vendor/drush/drush/includes/command.inc:178
PHP   7. _drush_invoke_hooks() /usr/lib/composer/vendor/drush/drush/includes/command.inc:210
PHP   8. call_user_func_array:{/usr/lib/composer/vendor/drush/drush/includes/command.inc:359}() /usr/lib/composer/vendor/drush/drush/includes/command.inc:359
PHP   9. drush_core_site_install() /usr/lib/composer/vendor/drush/drush/includes/command.inc:359
PHP  10. drush_core_site_install_version() /usr/lib/composer/vendor/drush/drush/commands/core/site_install.drush.inc:289
PHP  11. drush_op() /usr/lib/composer/vendor/drush/drush/commands/core/drupal/site_install.inc:78
PHP  12. drush_call_user_func_array() /usr/lib/composer/vendor/drush/drush/includes/drush.inc:705
PHP  13. install_drupal() /usr/lib/composer/vendor/drush/drush/includes/drush.inc:720
PHP  14. install_run_tasks() /vagrant/drupal/current/core/includes/install.core.inc:117
PHP  15. install_run_task() /vagrant/drupal/current/core/includes/install.core.inc:528
PHP  16. install_verify_requirements() /vagrant/drupal/current/core/includes/install.core.inc:650
PHP  17. install_check_requirements() /vagrant/drupal/current/core/includes/install.core.inc:1011
PHP  18. drupal_check_profile() /vagrant/drupal/current/core/includes/install.core.inc:2070

Fatal error: Call to a member function getPath() on a non-object in /vagrant/drupal/current/core/includes/install.inc on line 931

Call Stack:
    0.2022     235464   1. {main}() /usr/lib/composer/vendor/drush/drush/drush.php:0
    0.2022     235656   2. drush_main() /usr/lib/composer/vendor/drush/drush/drush.php:11
    0.5465    7574312   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /usr/lib/composer/vendor/drush/drush/drush.php:70
    0.6090    6343424   4. drush_dispatch() /usr/lib/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:62
    0.8194    8502672   5. call_user_func_array:{/usr/lib/composer/vendor/drush/drush/includes/command.inc:178}() /usr/lib/composer/vendor/drush/drush/includes/command.inc:178
    0.8194    8503248   6. drush_command() /usr/lib/composer/vendor/drush/drush/includes/command.inc:178
    0.8199    8504896   7. _drush_invoke_hooks() /usr/lib/composer/vendor/drush/drush/includes/command.inc:210
    0.9256    7859576   8. call_user_func_array:{/usr/lib/composer/vendor/drush/drush/includes/command.inc:359}() /usr/lib/composer/vendor/drush/drush/includes/command.inc:359
    0.9256    7860072   9. drush_core_site_install() /usr/lib/composer/vendor/drush/drush/includes/command.inc:359
    0.9271    7878816  10. drush_core_site_install_version() /usr/lib/composer/vendor/drush/drush/commands/core/site_install.drush.inc:289
    0.9338    8296080  11. drush_op() /usr/lib/composer/vendor/drush/drush/commands/core/drupal/site_install.inc:78
    0.9338    8297472  12. drush_call_user_func_array() /usr/lib/composer/vendor/drush/drush/includes/drush.inc:705
    0.9338    8297688  13. install_drupal() /usr/lib/composer/vendor/drush/drush/includes/drush.inc:720
    3.7297   24659784  14. install_run_tasks() /vagrant/drupal/current/core/includes/install.core.inc:117
    3.7400   24725800  15. install_run_task() /vagrant/drupal/current/core/includes/install.core.inc:528
    3.7400   24725840  16. install_verify_requirements() /vagrant/drupal/current/core/includes/install.core.inc:650
    3.7400   24728912  17. install_check_requirements() /vagrant/drupal/current/core/includes/install.core.inc:1011
    3.7400   24729056  18. drupal_check_profile() /vagrant/drupal/current/core/includes/install.core.inc:2070

Drush command terminated abnormally due to an unrecoverable error.                                       [error]
Error: Call to a member function getPath() on a non-object in
/vagrant/drupal/current/core/includes/install.inc, line 931
** BUILD ERROR: 'Install failed.'

**Comment by joesb** [comment]
Rebase ^

Installs fine for me now.

**Comment by lewisnyman** [comment]
Sorry I'm still getting the same error. I'm not sure if it's my drush version or something.

**Comment by joesb** [comment]
Hmm, that is really weird. For me …

```
$ drush --version
 Drush Version   :  8.0-dev 
```

**Comment by joesb** [comment]
Right, I've seen that getPath() error on a couple of site installs in recent days (not this one) and it usually happens *I think* (in all my *vast* D8 experience - ha!) when there's a dependency not installed available.

I'll look and see if there's something like that going on.

**Comment by joesb** [comment]
Hmm, do you have field_group contrib module installed in your local system?

```
projects[field_group][version] = 1.x-dev
projects[field_group][download][type] = "git"
projects[field_group][download][url] = http://git.drupal.org/project/field_group.git
projects[field_group][download][branch] = 8.x-1.x
projects[field_group][subdir] = contrib
```

… in .make file somewhere?

**Comment by iler** [comment]
I think Linkedin could also be added?

**Pull request merged**
