### PR TITLE
Adds WunderHub services module

### PR DESCRIPTION
**Pull request by joesb**
Includes
- Content types:
  - Service Areas
  - Services
- API endpoints:
  - /api/services - Service content list
  - /api/services/% - Service content item
  - /api/services/areas - Service Area content list
  - /api/services/areas/% - Service Area content item
  - /api/menutree/{menu_name} - menu tree of a specified menu, but menu needs to be 'allowed' in admin form at /admin/config/services/wunderhub
    - needs authentication

### CODE REVIEW

**Comment by lewisnyman** [comment]
What's the content strategy behind the heirachy of services and service areas? I don't see an example of this on wunder.uk or wunderkraut.com?

**Comment by lewisnyman** [comment]
> /api/menutree/{menu_name} - menu tree of a specified menu, but menu needs to be 'allowed' in admin form at /admin/config/services/wunderhub
Why do we need a menu tree? Is that how we would pull all services for one service area?

**Comment by joesb** [comment]
On wunder.uk homepage, the Service Areas are those 6 things on the homepage

**Comment by lewisnyman** [comment]
Ah ok so a service area would be something like training and then you would have types of training as services within that?

**Comment by joesb** [comment]
The menutree API is so that a subscribing site wanted to construct a menu of content (not just the services stuff, but any content in and any menu made available for the API), they can pull one from the hub site

**Comment by joesb** [comment]
Re services/areas: Yes, exactly - 'Drupal & Agile Training' service area encapsulates services Drupal training, agile training, agile coaching, etc, etc.

(Some services fit more than one area, of course)

**Comment by lewisnyman** [comment]
Which url would I hit to get all services in the "consulting" service area?

**Comment by joesb** [comment]
So with that last update :wink: I've add a query filter so you can filter like so:

```
/api/services?servicearea={some_term}
```
… where {some_term} is a 'contains' filter, so  

```
/api/services?servicearea=consulting
```
… would retrieve any services in service areas called e.g. Drupal Consulting OR Agile Consulting

**Comment by joesb** [comment]
Yay!

**Pull request merged**
